name: Deploy Todo App to AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  deploy:
    environment: production

    env:
      ALLOWED_ORIGINS: ${{ vars.ALLOWED_ORIGINS }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::610495549813:role/github-actions-lambda-deploy-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'

      - name: Install dependencies and create deployment package
        run: |
          cd backend
          rm -rf node_modules
          npm ci
          echo "Checking node_modules structure:"
          ls -la node_modules/ | grep express || echo "Express not found"
          zip -r ../deployment.zip . -x ".git/*" ".github/*" "README.md" ".gitignore" "logs/" ".env*"
          echo "Deployment package size:"
          ls -lh ../deployment.zip

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name to-do-app-express-api \
            --zip-file fileb://deployment.zip \
            --region ${{ env.AWS_REGION }}
